blank_issues_enabled: false
contact_links:
  - name: â“ Question or Other
    url: https://github.com/SupremeTechnopriest/react-idle-timer/discussions/new/choose
    about: Ask a question or start a discussion.
  - name: ğŸ“– Documentation
    url: https://idletimer.dev/
    about: Explore detailed documentation and examples.
  - name: ğŸ’¬ Join the Community
    url: https://discord.gg/YPuxNdWA4D
    about: Join our discord community for announcements and support.
